[package]
authors = ["Joe Ardent <code@ardent.nebcorp.com>"]
name = "arcaders"
version = "0.1.0"

[dependencies]
time = "0.1"

[dependencies.sdl2]
default-features = false
features = ["image", "ttf"]
version = "0.30"
